# Generated by Django 5.2.4 on 2025-08-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0002_motoinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='motos',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
