# Generated by Django 5.2.4 on 2025-09-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0003_motos_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='motos',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='motos/'),
        ),
    ]
