# Generated by Django 5.2.4 on 2025-08-31 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0003_motos_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motos',
            name='photo',
        ),
        migrations.CreateModel(
            name='ImagemMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='motos_adicionais/')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='motos.motos')),
            ],
        ),
    ]
