# Generated by Django 5.2.4 on 2025-09-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0004_motos_photo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='motos',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='motos/'),
        ),
        migrations.AddField(
            model_name='motos',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='motos/'),
        ),
        migrations.AddField(
            model_name='motos',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='motos/'),
        ),
        migrations.AddField(
            model_name='motos',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='motos/'),
        ),
    ]
